### ISSUE TITLE
The workflow of Docker

### ISSUE THREAD

**Issue by robinvalk** [MD-Meetup/talks#2]
From creating an image to deploying it to production.
Not so much the commands etc. because you'll learn that when you start using it.

This talk can be given by @koenvdheuvel, @robinvalk.

Input appriciated via comments below.

**Comment by robinvalk** [comment]
Maybe this will be covered by merapar.com/meetup.

**Comment by koenhoeijmakers** [comment]
What about this one, we've had the meetup at Merapar, will we do a follow up? or wouldn't this make any sense as Merapar might do a docker 2.0?

**Comment by robinvalk** [comment]
I think Merapar isn't planning on doing a docker 2.0 version. Next topic is expected to be in Q1 2018 with the topic: Kubernetes.

**Comment by koenvdheuvel** [comment]
@koenhoeijmakers What topic(s) would you like to see covered in a "2.0"?

**Comment by robinvalk** [comment]
Update: Merapar's next meetup is probably not going to be about Kubernetes, neither Docker 2.0.

@koenhoeijmakers still have the same mindset about this? And what topic(s)?
