### ISSUE TITLE
Laravel Testing Suite 101

### ISSUE THREAD

**Issue by JoeriAben** [MD-Meetup/talks#3]
Laravel Testing suite 101. The basics of testing in laravel and the best practice to setup.

Continuation of #1

**Comment by robinvalk** [comment]
Testing is a little vague @JoeriAben 
You have loads of testing methods. What topics do you want to cover?
See this question for testing topics:
https://stackoverflow.com/questions/4904096/whats-the-difference-between-unit-functional-acceptance-and-integration-test

**Comment by koenhoeijmakers** [comment]
#1 Discussions have been moved to this issue instead.

**Comment by koenhoeijmakers** [comment]
To me a focus on Unit Testing and maybe TDD (Test Driven Development) would be nice :), i'd say Unit Testing would be a nice subject for a single talk.

**Comment by robinvalk** [comment]
Agreed, I think we should re-open idea #1 and dedicate it testing methods.

TDD can nicely be combined with this talk idea.

**Comment by koenvdheuvel** [comment]
Can possibly do this after gaining experience at new Job with unit testing.

**Comment by robinvalk** [comment]
@koenvdheuvel Maybe better for idea #1 then, as your new job will not be Laravel?
