### ISSUE TITLE
Creating an IoT device

### ISSUE THREAD

**Issue by robinvalk** [MD-Meetup/talks#5]
Creating and deploying an IoT device in the wild.
Possible subjects:
- AWS IoT
- LoRa
- Simple devices to start with (comparison?)

**Comment by robinvalk** [comment]
@koenvdheuvel You had a small arduino chip thingy right? Could you send me some resources of that?

**Comment by koenvdheuvel** [comment]
http://esp32.net
http://esp8266.net

**Comment by robinvalk** [comment]
I have now read more upon the subject. I'm ashamed of my "small arduino chip thingy" description ^^. Although, technically it's not completely wrong.

**Comment by robinvalk** [comment]
Basics of MQTT, reference blog posts: https://www.hivemq.com/blog/mqtt-essentials/
